### ISSUE TITLE
neko reframe benchmark

### ISSUE THREAD

**Issue by jigo3635** [Lumi-supercomputer/lumi-reframe-tests#47]
There is one _neko_ branch 

[https://github.com/Lumi-supercomputer/lumi-reframe-tests/tree/neko](https://github.com/Lumi-supercomputer/lumi-reframe-tests/tree/neko)

In` lumi-reframe-tests/checks/apps/neko/ `, there are two python check scripts, both originally are from csc. 

1) `neko_n1_8gpu_24.03.py `(hardcode to run 1node with 8 gpus on small-g for tgv 32 case 32*3), to run it 

`reframe -C lumi_setting.py -c checks/apps/neko/checks.py checks/apps/neko/neko_n1_8gpu_24.03.py -r
`
where **lumi_setting.py**  is different from **lumi.py** (did not make it works on GPU) in branch and

In _neko_n1_8gpu_24.03.py_ 
```

class MakeNeko(rfm.core.buildsystems.BuildSystem):
    srcfile = variable(str, type(None), value=None)

    def __init__(self):
        self.makeneko = os.path.join('/project/project_462000008/jigong2/neko/0.8.1/', 'bin', 'makeneko')
```

So, the script just uses pre-installed neko and does not compiler neko from source code.

issues for this script:

*  how to specify different number of nodes (num_nodes=[1, 2, 4, 8]) for different cases e.g. tgv16 (16^3 elements), tgv32 ( 32^3 elements) etc.  in one script

**Comment by mszpindler** [comment]
- [ ] Separate `makeneko` in the external module
- [ ] Get custom (1) test to run
- [ ] Agree config settings with generic one
- [ ] Split test input cases into differen directories
- [ ] Parametrize custom test to run with multiple node/gpus configuration

**Comment by mszpindler** [comment]
- [ ] Add larger case
