### ISSUE TITLE
Pytorch Distributed Example Bug

### ISSUE THREAD

**Issue by brynluisi** [Lumi-supercomputer/lumi-reframe-tests#55]
I believe I found a bug in the [mnist_DDP.py]( https://github.com/Lumi-supercomputer/lumi-reframe-tests/blob/main/checks/containers/ML_containers/src/pytorch/mnist/mnist_DDP.py) example provided by Lumi.

```python
def average_gradients(model):
    """ Gradient averaging. """
    size = float(dist.get_world_size())
    group = dist.new_group([0])
    for param in model.parameters():
        dist.all_reduce(param.grad.data, op=dist.reduce_op.SUM, group=group)
        param.grad.data /= size
```

First, `average_gradients()` is called for every batch and a new group object is instantiated every time. I believe it only needs to be created once. Second, `dist.new_group([0])` only includes the first gpu. The combination of these two leads to memory quickly being exhausted. The snippet below fixed this memory error: 

```python
group = dist.new_group([i for i in dist.world_size()])


def average_gradients(model, group):
    """ Gradient averaging. """
    size = float(dist.get_world_size())
    for param in model.parameters():
        dist.all_reduce(param.grad.data, op=dist.reduce_op.SUM, group=group)
        param.grad.data /= size
```

**Comment by mihkeltiks** [comment]
Indeed, somehow a buggy version of a general example has somehow been included here. This was to only be considered as an idea of how to configure the environment, launch and test if it works or something has been changed - thus the code did not get much attention. 
You are also correct in the group idea, but you could in general just remove the group variable and parameter, and it would work the same. However, this manual gradient averaging method is not something that is recommended any more either. Using DDP, one can overlap the communications that are included in this step with the previous one, providing more performance: https://pytorch.org/docs/master/notes/ddp.html
Thank you for bringing our attention to this! I will swap this out for a more up to date and suitable example.
